### ISSUE TITLE
manually triggering the progress bar with wire:loading

### ISSUE THREAD

**Issue by atmonshi** [njxqlus/filament-progressbar#3]
### What happened?

This is not a bug just a question. :)

In customer pages, if I have some actions how can I manually show the progress bar

I have something like this:

```html
<div>

        <div wire:loading>
            loading data...
        </div>
        
        <form>
            {{ $this->form }}

            <button type="submit">
                Submit
            </button>
        </form>

        <x-filament-actions::modals />
    </div>
```

### How to reproduce the bug

-

### Package Version

last

### PHP Version

8.2

### Laravel Version

10

**Comment by njxqlus** [comment]
This package is the [pace.js](https://codebyzach.github.io/pace/) library. Pacejs is an automatic page load progress bar and showing of the progress bar is controlled by JS. I'm not sure that your request is possible because this package just integrates JS and CSS files with color customization.

**Comment by atmonshi** [comment]
I see, thank you for the clarification :)
