### ISSUE TITLE
[Bug]: Works but Shows Console Error

### ISSUE THREAD

**Issue by abbasmashaddy72** [njxqlus/filament-progressbar#5]
### What happened?

`Uncaught Error: Permission denied to access property "apply"`

### How to reproduce the bug

Just Simple Installed it as Instructed But it Works But in Console Shows Error

### Package Version

1.0

### PHP Version

PHP 8.2

### Laravel Version

v10.10

### Which operating systems does with happen with?

Windows, Linux

**Comment by njxqlus** [comment]
@abbasmashaddy72 hello! Thank you for using this package.

I tried to update for latest version of Laravel, Filament and Livewire and I got no errors in console. 

This package is using [Pace.js](https://github.com/CodeByZach/pace/) v 1.2.4 which is the latest for now. Maybe there are some problems with other packages, version of Node?

**Comment by abbasmashaddy72** [comment]
This is my Package.json Lets me know if anything I am missing out So that I can add it

Package.json:

```
{
    "private": true,
    "type": "module",
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "devDependencies": {
        "@alpinejs/focus": "^3.13.5",
        "@awcodes/alpine-floating-ui": "^3.5.0",
        "@tailwindcss/forms": "^0.5.7",
        "@tailwindcss/typography": "^0.5.10",
        "alpinejs": "^3.13.5",
        "autoprefixer": "^10.4.17",
        "axios": "^1.6.4",
        "cropperjs": "^1.6.1",
        "laravel-vite-plugin": "^1.0.0",
        "postcss": "^8.4.33",
        "postcss-nesting": "^12.0.2",
        "sass": "^1.70.0",
        "tailwindcss": "^3.4.1",
        "tippy.js": "^6.3.7",
        "vite": "^5.0.0"
    },
    "dependencies": {
        "flowbite": "^2.2.1",
        "remixicon": "^4.1.0",
        "tobii": "^2.0.0-alpha"
    }
}
```

**Comment by abbasmashaddy72** [comment]
I am using Node 18 and Except Your Package I have not installed any other package in repo pace.js as you mentioned do I need to install that package too

**Comment by njxqlus** [comment]
I'm also using Node 18 and there is my package.json:

```
{
    "private": true,
    "type": "module",
    "scripts": {
        "dev": "vite",
        "build": "vite build"
    },
    "devDependencies": {
        "@alpinejs/focus": "^3.10.5",
        "@shufo/prettier-plugin-blade": "^1.11.1",
        "@tailwindcss/forms": "^0.5.4",
        "@tailwindcss/typography": "^0.5.9",
        "alpinejs": "^3.0.6",
        "autoprefixer": "^10.4.14",
        "axios": "^1.1.2",
        "laravel-vite-plugin": "^0.7.5",
        "postcss": "^8.4.27",
        "prettier": "^3.0.2",
        "tailwindcss": "^3.3.3",
        "vite": "^4.0.0"
    }
}
```

You don't need to do extra actions except that mentioned in readme.

Can you check thought the devtools which file fires this error in console?
